AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Weather Station API

Resources:
  WeatherStationFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: src/
      Handler: aws_wsgi.handler
      Runtime: python3.12
      VpcConfig:
        SecurityGroupIds: [ sg-07c60cec7e5f0e956 ]
        SubnetIds:
          - subnet-050466863802331de
          - subnet-0eb3f2e82007956d2
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          DB_SECRET_ARN: "arn:aws:secretsmanager:us-east-1:832362088918:secret:eather-api/db-credentials-VDOHVm"
          WSGI_APP: app.app
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - SecretsManagerReadOnly

Outputs:
  ApiUrl:
    Description: "API URL"
    Value: !Sub "https://://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"