AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple API to ingest and retrieve weather station data.

Resources:
  WeatherStationApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,x-api-key'"
        AllowOrigin: "'*'"

  AppDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: dependencies/
      CompatibleRuntimes:
        - python3.11

  WeatherStationFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: src/
      Handler: aws_wsgi.handler
      Runtime: python3.11
      Layers:
        - !Ref AppDependenciesLayer
      Events:
        ApiEvents:
          Type: Api
          Properties:
            RestApiId: !Ref WeatherStationApi
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          DB_SECRET_ARN: "arn:aws:secretsmanager:us-east-1:832362088918:secret:eather-api/db-credentials-VDOHVm"
          WSGI_APP: app.app
      Policies:
        - SecretsManagerReadPolicy:
            SecretName: "arn:aws:secretsmanager:us-east-1:832362088918:secret:eather-api/db-credentials-VDOHVm"

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://://${WeatherStationApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"